apiVersion: v1
kind: Service
metadata:
  name: term-server-service
  namespace: dep-1
spec:
  selector:
    app: term-server-deployment
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
